#!/usr/bin/env python3
"""nexsnap.py — unified corpus + state generator.

Produces two artifacts on each run:
  1. CORPUS.md at repo root — comprehensive architectural overview
     auto-generated from DOCTRINE, FACULTY_MODEL, SENTIENCE_TRANSLATION_MAP,
     spec docs, source modules, schema files, GUI routes, and runtime DBs.
     This file is regenerated; do not hand-edit.
  2. snapshots/YYYY-MM-DD_HHMM_state.json — runtime state snapshot
     (drives, voice_profile, fountain, gate decisions, etc.)

Imports extractors from nexsnap_extract.py (read-only inspection).
Then assembles them into structured markdown for Claude bootstrap.

Usage:
  python3 scripts/nexsnap.py              # generate corpus + state, no commit
  python3 scripts/nexsnap.py --commit     # generate + git add + git commit + push

The --commit flag wraps the entire output in one git transaction so the
corpus and state snapshot stay paired.
"""
from __future__ import annotations

import json
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

# Make extractors importable
SCRIPT_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPT_DIR))
import nexsnap_extract as ex

REPO = Path("/home/rr/Desktop/Desktop/nex5")
CORPUS_PATH = REPO / "CORPUS.md"
SNAP_DIR = REPO / "snapshots"


def write_state_json(snap_ts):
    """Write the runtime state snapshot to snapshots/."""
    SNAP_DIR.mkdir(parents=True, exist_ok=True)
    fname = datetime.fromtimestamp(snap_ts).strftime("%Y-%m-%d_%H%M") + "_state.json"
    path = SNAP_DIR / fname

    state = {
        "snapshot_at": snap_ts,
        "snapshot_at_str": datetime.fromtimestamp(snap_ts).strftime("%Y-%m-%d %H:%M:%S"),
        "runtime": ex.extract_runtime_state(),
        "port_status_counts": _port_counts(ex.extract_port_status()),
        "fountain_by_branch_24h": ex.extract_runtime_state().get("fountain_24h_by_branch", {}),
    }
    path.write_text(json.dumps(state, indent=2, default=str))
    return path


def _port_counts(port_data):
    """Normalize status strings and count."""
    if not port_data or "rows" not in port_data:
        return {}
    counts = {}
    for row in port_data["rows"]:
        status = row.get("status", "")
        if "DONE" in status:
            key = "DONE"
        elif "UNBLOCKED" in status:
            key = "UNBLOCKED"
        elif "QUEUED" in status:
            key = "QUEUED"
        elif "DESIGN-COMPLETE" in status:
            key = "DESIGN-COMPLETE"
        elif "DEFERRED" in status:
            key = "DEFERRED"
        else:
            key = "OTHER"
        counts[key] = counts.get(key, 0) + 1
    return counts


def assemble_corpus(snap_ts):
    """Produce the full CORPUS.md content."""
    snap_str = datetime.fromtimestamp(snap_ts).strftime("%Y-%m-%d %H:%M:%S")

    # Extract once, reuse
    doctrine = ex.extract_doctrine_principles()
    faculty = ex.extract_faculty_outcomes()
    port = ex.extract_port_status()
    stages = ex.extract_theory_x_stages()
    stage_map = ex.extract_stage_map()
    schema = ex.extract_substrate_schema()
    routes = ex.extract_gui_routes()
    spec_docs = ex.extract_spec_docs()
    amendments = ex.extract_amendments()
    anti_patterns = ex.extract_anti_patterns()
    runtime = ex.extract_runtime_state()
    unmapped = ex.extract_unmapped_roster()

    parts = []
    parts.append("# NEX CORPUS")
    parts.append("")
    parts.append("*Auto-generated by scripts/nexsnap.py. Do not edit by hand.*")
    parts.append("*Edit DOCTRINE.md, SENTIENCE_TRANSLATION_MAP.md, FACULTY_MODEL.md,*")
    parts.append("*or the source modules. This file regenerates from them.*")
    parts.append("")
    parts.append("Generated: " + snap_str)
    parts.append("")
    parts.append("---")
    parts.append("")
    parts.append("## How to use this file")
    parts.append("")
    parts.append("Any session of Claude opening the nex5 repo should read this file first.")
    parts.append("It is the architectural bootstrap. Source files are authoritative; this")
    parts.append("is a navigation map and a state snapshot.")
    parts.append("")
    parts.append("If something here contradicts a source file, the source file wins.")
    parts.append("Tell Jon the corpus has drifted; regenerate via `python3 scripts/nexsnap.py`.")
    parts.append("")
    parts.append("---")
    parts.append("")

    # §1 What nex is
    parts.append("## §1 What nex is")
    parts.append("")
    parts.append(doctrine.get("s1_purpose", "(extract failed)"))
    parts.append("")
    parts.append("---")
    parts.append("")

    # §2 Architectural commitment
    parts.append("## §2 Architectural commitment (DOCTRINE §3)")
    parts.append("")
    parts.append(doctrine.get("s3_architecture", "(extract failed)"))
    parts.append("")
    parts.append("---")
    parts.append("")

    # §3 Faculty model
    parts.append("## §3 Faculty model — the four outcomes")
    parts.append("")
    parts.append("### Coherence Gate")
    parts.append("")
    parts.append(faculty.get("coherence_gate", "(extract failed)"))
    parts.append("")
    parts.append("### Four outcomes")
    parts.append("")
    parts.append(faculty.get("four_outcomes", "(extract failed)"))
    parts.append("")
    parts.append("---")
    parts.append("")

    # §4 Port status table
    parts.append("## §4 Port status (DOCTRINE §5)")
    parts.append("")
    counts = _port_counts(port)
    parts.append("**Counts:** " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))
    parts.append("")
    parts.append("| # | Node | Status |")
    parts.append("|---|------|--------|")
    for row in port.get("rows", []):
        status = row.get("status", "").replace("|", "/")
        node = row.get("node", "").replace("|", "/")
        parts.append(f"| {row.get('num', '')} | {node} | {status} |")
    parts.append("")
    parts.append("---")
    parts.append("")

    # §5 Theory X stage map
    parts.append("## §5 Stage map (theory_x/)")
    parts.append("")
    parts.append("Each stage directory is a Theory X stage or stage-extension.")
    parts.append("Line counts show source size at generation time.")
    parts.append("")
    for stage in stage_map:
        name = stage["stage"]
        docstring = next((s["doc"] for s in stages if s["name"] == name), "")
        parts.append(f"### {name}")
        if docstring:
            parts.append(f"*{docstring}*")
        parts.append("")
        for f in stage["files"]:
            parts.append(f"  - {f['name']} ({f['lines']} lines)")
        parts.append("")
    parts.append("---")
    parts.append("")

    # §6 Substrate schema
    parts.append("## §6 Substrate (5 databases)")
    parts.append("")
    parts.append("All writes go through `substrate.Writer`. Direct sqlite3.connect outside")
    parts.append("`substrate/` is a bug per DOCTRINE §8 anti-pattern.")
    parts.append("")
    for db, tables in schema.items():
        parts.append(f"### {db}.db")
        for t in tables:
            parts.append(f"  - {t}")
        parts.append("")
    parts.append("---")
    parts.append("")

    # §7 GUI routes
    parts.append("## §7 GUI surface (gui/server.py)")
    parts.append("")
    parts.append("Flask routes exposing nex to the HUD and to programmatic clients.")
    parts.append("")
    seen = set()
    for r in routes:
        key = (r["method"], r["path"])
        if key in seen:
            continue
        seen.add(key)
        parts.append(f"  - `{r['method']:6s} {r['path']}`")
    parts.append("")
    parts.append("---")
    parts.append("")

    # §8 Spec docs index
    parts.append("## §8 Spec documents (theory_x/*.md)")
    parts.append("")
    parts.append("Foundational and design documents. Read in source for full content;")
    parts.append("this is just the index.")
    parts.append("")
    for d in spec_docs:
        parts.append(f"  - **{d['name']}** ({d['size_kb']} KB, last edit {d['mtime']})")
    parts.append("")
    parts.append("---")
    parts.append("")

    # §9 Recent amendments
    parts.append("## §9 Recent doctrine amendments")
    parts.append("")
    parts.append("From DOCTRINE.md amendment chain. Most recent first in build order.")
    parts.append("")
    for a in amendments:
        parts.append(f"- {a}")
    parts.append("")
    parts.append("---")
    parts.append("")

    # §10 Anti-patterns
    parts.append("## §10 Anti-patterns (DOCTRINE §8)")
    parts.append("")
    parts.append("Observed failure modes from prior sessions. Not hypothetical.")
    parts.append("")
    for ap in anti_patterns:
        parts.append(f"- **{ap['name']}** — {ap['summary']}")
    parts.append("")
    parts.append("---")
    parts.append("")

    # §11 Unmapped roster
    parts.append("## §11 What's not yet built (unmapped roster)")
    parts.append("")
    parts.append("Sentience 5.5 cognitive nodes with named functions, no nex5 port yet.")
    parts.append("Source: SENTIENCE_TRANSLATION_MAP.md Tier A/B/C tables.")
    parts.append("")
    for tier_key in ("tier_A", "tier_B", "tier_C"):
        if tier_key not in unmapped:
            continue
        tier_letter = tier_key.split("_")[1]
        labels = {"A": "high port value", "B": "moderate port value",
                  "C": "borderline / §7 tension"}
        parts.append(f"### Tier {tier_letter} — {labels.get(tier_letter, '')}")
        parts.append("")
        for row in unmapped[tier_key]:
            nodes = ", ".join(f"`{n}`" for n in row["nodes"])
            parts.append(f"  - {nodes} — {row['function']}")
        parts.append("")
    parts.append("---")
    parts.append("")

    # §12 Current runtime state
    parts.append("## §12 Current runtime state at generation")
    parts.append("")
    drives = runtime.get("drives", {})
    if drives:
        parts.append("### Drives")
        parts.append("")
        for k in ("coherence", "exploration", "integration",
                  "self_preservation", "curiosity"):
            v = drives.get(k, 0.0)
            parts.append(f"  - {k}: {v:.3f}")
        if drives.get("tension_pairs"):
            parts.append(f"  - tension: {drives['tension_pairs']}")
        parts.append("")
    vp = runtime.get("voice_profile", [])
    if vp:
        parts.append("### voice_profile")
        for entry in vp:
            parts.append(f"  - {entry['pair']}: {entry['freq']} fires")
        parts.append("")
    fb = runtime.get("fountain_24h_by_branch", {})
    if fb:
        parts.append("### Fountain by hot_branch (24h)")
        for branch, n in sorted(fb.items(), key=lambda x: -x[1]):
            parts.append(f"  - {branch}: {n}")
        parts.append("")
    gate = runtime.get("gate_24h", {})
    if isinstance(gate, dict) and gate:
        total = sum(gate.values()) or 1
        parts.append("### Gate decisions (24h)")
        for outcome, n in sorted(gate.items(), key=lambda x: -x[1]):
            pct = 100 * n / total
            parts.append(f"  - {outcome}: {n} ({pct:.1f}%)")
        parts.append("")
    parts.append("---")
    parts.append("")

    # §13 Anti-drift rules
    parts.append("## §13 Anti-drift rules for working on nex")
    parts.append("")
    parts.append("Findings from prior sessions, encoded here so future-Claude does not")
    parts.append("rediscover them by trial and error.")
    parts.append("")
    parts.append("**Architecture:**")
    parts.append("")
    parts.append("- The belief field thinks; the LLM vocalizes (DOCTRINE §3). Faculty nodes")
    parts.append("  do not couple directly — coordination is mediated through substrate.")
    parts.append("- Every generative thought passes through CoherenceGate; the gate decides")
    parts.append("  ACCEPT / REJECT / HOLD / RESHAPE.")
    parts.append("- substrate_voice is a separate fountain write-path with anchor_belief_id")
    parts.append("  FK to the locked T1/T2 belief being voiced. It is not LLM-generated; it")
    parts.append("  is LLM-rephrased anchor content.")
    parts.append("- hot_branch=='quiescent' means fountain fire with no dominant branch.")
    parts.append("  Feed-paste content is identified by `[branch.name]` prefix, not by")
    parts.append("  hot_branch alone.")
    parts.append("")
    parts.append("**Measurement:**")
    parts.append("")
    parts.append("- voice_profile.signature_vocabulary is computed against ALL fires under")
    parts.append("  a drive-pair across all time. It is slow to shift; recent register")
    parts.append("  changes can be invisible for days because of historical mass.")
    parts.append("- voice_profile.frequency updates live (count) but signature_vocabulary")
    parts.append("  is hourly recompute, dominated by cumulative window.")
    parts.append("- For recent-vs-cumulative comparisons, use")
    parts.append("  `scripts/voice_profile_recent_vs_cumulative.py`.")
    parts.append("")
    parts.append("**Verification:**")
    parts.append("")
    parts.append("- A node is wired if its output reaches a §3 integration surface on a")
    parts.append("  real /api/chat request. Indirect injection via routers/membranes is")
    parts.append("  valid. Do not audit by call-site grep (DOCTRINE §8 anti-pattern).")
    parts.append("- Unit tests verify mechanisms, not wiring. Wiring requires a real")
    parts.append("  HUD query.")
    parts.append("- Smoke set must split OUTSIDE-route checks (Conversational/Technical)")
    parts.append("  from INSIDE-route checks (Philosophical/self-inquiry).")
    parts.append("")
    parts.append("**Process discipline:**")
    parts.append("")
    parts.append("- Each session delivers a complete node or foundational document.")
    parts.append("  No partial wiring (DOCTRINE §1).")
    parts.append("- Each amendment to DOCTRINE.md or DIRECTION.md is committed with")
    parts.append("  a message describing what changed and what was learned (§9).")
    parts.append("- Phase gates require Jon's explicit greenlight (DOCTRINE §8).")
    parts.append("")
    parts.append("---")
    parts.append("")
    parts.append(f"*Last regenerated: {snap_str}*")
    parts.append("")

    return "\n".join(parts)


def git_commit(corpus_path, state_path):
    """Add, commit, push corpus + state snapshot."""
    snap_label = datetime.now().strftime("%Y-%m-%d %H:%M")
    msg_lines = [
        f"corpus: regenerated {snap_label}",
        "",
        "Auto-regenerated by scripts/nexsnap.py.",
        "",
        "Includes:",
        "- CORPUS.md (architectural overview, §1-§13)",
        f"- {state_path.name} (runtime state snapshot)",
        "",
        "Re-run with `python3 scripts/nexsnap.py --commit` to regenerate.",
    ]
    subprocess.run(["git", "-C", str(REPO), "add",
                    str(corpus_path), str(state_path)], check=True)
    subprocess.run(["git", "-C", str(REPO), "commit", "-m", "\n".join(msg_lines)],
                   check=True)
    subprocess.run(["git", "-C", str(REPO), "push", "origin", "main"], check=True)


def main():
    snap_ts = time.time()
    corpus_text = assemble_corpus(snap_ts)
    CORPUS_PATH.write_text(corpus_text)
    state_path = write_state_json(snap_ts)
    print(f"OK CORPUS.md written ({len(corpus_text)} bytes)")
    print(f"OK state snapshot at {state_path}")
    if "--commit" in sys.argv:
        print("Committing...")
        git_commit(CORPUS_PATH, state_path)
        print("OK pushed to origin/main")


if __name__ == "__main__":
    main()
