"""Theory X — Coherence Gate.

Per FACULTY_MODEL.md §2.3-2.4 (committed 59c20d6).

Every thought generated by a faculty node passes through this gate
before joining the substrate. The gate reads NEX's current substrate
state and applies the current question set:

  1. Does this contradict what NEX currently holds?
  2. Does this connect to what NEX is currently engaged with?
  3. Is this novel or redundant?

Returns one of four outcomes: ACCEPT, REJECT, HOLD, RESHAPE.

Phase 22 scope:
  - HOLD and RESHAPE are logged but not acted on (soft rejects).
    Phase 23 builds the holding zone; Phase 24 builds reshape path.
  - Decision thresholds are v1; expected to tune from production data.

Design commitments (FACULTY_MODEL.md + 2026-05-10 session):
  - Universal: no generative path bypasses the gate.
  - Fast: fresh reads per call (Option α); substrate reads are cheap.
  - Quality gate runs first (existing _quality_check), gate runs after.
"""
from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

import errors
from substrate import Reader, Writer

THEORY_X_STAGE = "gate"
_LOG_SOURCE = "coherence_gate"

# ── Negation words — reused from harmonizer pattern ──────────────────────────

_NEGATION_WORDS = frozenset({
    "not", "no", "never", "cannot", "isn't", "aren't", "doesn't",
    "don't", "won't", "without", "lack", "lacks", "absent",
})
_NOT_ADDITIVE_RE = re.compile(r'\bnot\s+(?:only|just)\b', re.IGNORECASE)
_STOPWORDS = frozenset({
    "a", "an", "the", "is", "are", "was", "were", "be", "been",
    "do", "does", "did", "have", "has", "had", "will", "would",
    "can", "could", "should", "may", "might", "shall",
    "i", "you", "he", "she", "it", "we", "they",
    "what", "how", "why", "when", "where", "which", "who",
    "this", "that", "these", "those", "and", "or", "but",
    "of", "in", "on", "at", "to", "for", "with", "about",
    "not", "no", "so", "if", "as",
})


# ── Thresholds ────────────────────────────────────────────────────────────────

# Jaccard ≥ this → REJECT (redundant)
_REDUNDANCY_THRESHOLD = 0.70
# Minimum packet confidence to fire a SelfNarrative write on problem-relevant ACCEPT
_NARRATIVE_CONFIDENCE_THRESHOLD = 0.60
# Jaccard in [this, _REDUNDANCY_THRESHOLD) → HOLD (similar but not duplicate)
_HOLD_JACCARD_LOW = 0.40
# Minimum content-word overlap to count as "connecting to goal/problem"
_GOAL_CONNECT_OVERLAP = 2
# Recent beliefs window for redundancy check
_RECENT_LIMIT = 50
# T1 locked anchors — no limit; check all of them
_ANCHOR_LIMIT = 500


# ── Data structures ───────────────────────────────────────────────────────────

class GateOutcome(str, Enum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    HOLD = "HOLD"
    RESHAPE = "RESHAPE"


@dataclass
class GateDecision:
    outcome: GateOutcome
    reason: str
    latency_ms: float = 0.0


@dataclass
class ThoughtPacket:
    """A thought about to enter the substrate, with provenance metadata."""
    content: str
    source_node: str   # e.g. 'fountain', 'synergizer', 'stage2_crystallization'
    confidence: float
    branch_id: Optional[str] = None
    metadata: dict[str, Any] = field(default_factory=dict)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _tokens(text: str) -> set[str]:
    """Lowercase content-word tokens, stripped of punctuation and stopwords."""
    punct = '.,?!;:\'"'
    return {
        w.strip(punct)
        for w in text.lower().split()
        if w.strip(punct) and w.strip(punct) not in _STOPWORDS and len(w.strip(punct)) > 2
    }


def _jaccard(a: str, b: str) -> float:
    wa = _tokens(a)
    wb = _tokens(b)
    if not wa or not wb:
        return 0.0
    return len(wa & wb) / len(wa | wb)


def _has_negation(text: str) -> bool:
    cleaned = _NOT_ADDITIVE_RE.sub('', text)
    words = set(cleaned.lower().split())
    return bool(words & _NEGATION_WORDS)


# ── Gate ──────────────────────────────────────────────────────────────────────

class CoherenceGate:
    """
    Coherence Gate — reads NEX's substrate, applies the question set,
    returns a GateDecision for every incoming ThoughtPacket.

    Implements the SentienceNode protocol (DOCTRINE §4) for registration
    and monitoring. The gate itself is stateless: its decisions are
    functions of the substrate it reads, not of prior gate state.
    """

    name: str = "coherence_gate"

    def __init__(
        self,
        beliefs_reader: Reader,
        beliefs_writer: Writer,
        conversations_reader: Optional[Reader] = None,
        holding_zone=None,       # Phase 23: HoldingZone instance
        resolver=None,            # Phase 23: HoldingZoneResolver instance
        trigger_detector=None,   # Phase 25a TN-1: TriggerDetector instance
        self_narrative=None,     # Phase 26: SelfNarrative instance
    ) -> None:
        self._beliefs_reader = beliefs_reader
        self._beliefs_writer = beliefs_writer
        self._conversations_reader = conversations_reader
        self._holding_zone = holding_zone
        self._resolver = resolver
        self._trigger_detector = trigger_detector
        self._self_narrative = self_narrative
        self._decision_count: int = 0

    # ── Public API ────────────────────────────────────────────────────────────

    def check(self, packet: ThoughtPacket) -> GateDecision:
        """Evaluate an incoming thought against the current substrate.

        Returns a GateDecision with outcome and reason. Logs the decision
        to gate_decisions table. Never raises — on internal error returns
        ACCEPT so existing paths are not broken.
        """
        t0 = time.perf_counter()
        try:
            decision = self._evaluate(packet)
        except Exception as exc:
            errors.record(
                f"coherence_gate error: {exc}", source=_LOG_SOURCE, exc=exc
            )
            decision = GateDecision(outcome=GateOutcome.ACCEPT, reason="gate_error_fallback")

        decision.latency_ms = (time.perf_counter() - t0) * 1000.0
        self._log_decision(packet, decision)
        self._decision_count += 1

        # Phase 23 — Holding Zone: persist HOLD; check held zone on ACCEPT
        # Phase 24 — RESHAPE: enqueue to reshape_pending for resolver processing
        # Phase 25a TN-1 — REJECT: log trigger for potential throw-net session
        if decision.outcome == GateOutcome.REJECT and self._trigger_detector is not None:
            try:
                self._trigger_detector.record_gate_reject(packet, decision)
            except Exception as exc:
                errors.record(
                    f"trigger_detector.record_gate_reject error: {exc}",
                    source=_LOG_SOURCE, exc=exc,
                )

        if decision.outcome == GateOutcome.HOLD and self._holding_zone is not None:
            try:
                self._holding_zone.hold(packet, decision.reason)
            except Exception as exc:
                errors.record(
                    f"holding_zone.hold error: {exc}", source=_LOG_SOURCE, exc=exc
                )
        elif decision.outcome == GateOutcome.RESHAPE and self._holding_zone is not None:
            try:
                reshape_depth = packet.metadata.get("reshape_depth", 0)
                self._holding_zone.put_reshape_pending(packet, reshape_depth)
            except Exception as exc:
                errors.record(
                    f"holding_zone.put_reshape_pending error: {exc}",
                    source=_LOG_SOURCE, exc=exc,
                )
        elif decision.outcome == GateOutcome.ACCEPT and self._resolver is not None:
            try:
                self._resolver.on_gate_accept(packet)
            except Exception as exc:
                errors.record(
                    f"resolver.on_gate_accept error: {exc}", source=_LOG_SOURCE, exc=exc
                )

        return decision

    # ── SentienceNode protocol ────────────────────────────────────────────────

    def tick(self, context: dict[str, Any] = None) -> dict[str, Any]:
        return self.state()

    def decay(self, now: float) -> None:
        pass  # gate is stateless; nothing to decay

    def state(self, now: float = None) -> dict[str, Any]:
        return {
            "name": self.name,
            "decisions_this_session": self._decision_count,
        }

    # ── Evaluation ────────────────────────────────────────────────────────────

    def _evaluate(self, packet: ThoughtPacket) -> GateDecision:
        content = packet.content
        tok = _tokens(content)
        neg = _has_negation(content)

        anchors, goals, problems, recent = self._read_substrate()

        # Check 1a — Redundancy (Jaccard ≥ 0.70 → REJECT)
        for row in recent:
            j = _jaccard(content, row["content"])
            if j >= _REDUNDANCY_THRESHOLD:
                return GateDecision(
                    outcome=GateOutcome.REJECT,
                    reason=f"redundant:{j:.2f}",
                )

        # Check 1b — Direct negation of a locked T1 anchor → REJECT
        for anchor in anchors:
            anchor_tok = _tokens(anchor["content"])
            anchor_neg = _has_negation(anchor["content"])
            overlap = len(tok & anchor_tok)
            if overlap >= 4 and (neg != anchor_neg):
                return GateDecision(
                    outcome=GateOutcome.REJECT,
                    reason=f"contradicts_anchor:locked_id_{anchor['id']}",
                )

        # Check 2a — Jaccard in [0.40, 0.70) → HOLD (similar, uncertain)
        for row in recent:
            j = _jaccard(content, row["content"])
            if _HOLD_JACCARD_LOW <= j < _REDUNDANCY_THRESHOLD:
                return GateDecision(
                    outcome=GateOutcome.HOLD,
                    reason=f"hold:jaccard_{j:.2f}",
                )

        # Check 2b — Negates active goal or problem framing → HOLD
        for g in goals:
            g_tok = _tokens(g["title"] or "")
            if len(tok & g_tok) >= _GOAL_CONNECT_OVERLAP and neg:
                return GateDecision(
                    outcome=GateOutcome.HOLD,
                    reason=f"hold:negates_goal_{g['id']}",
                )
        for p in problems:
            p_tok = _tokens(p["title"] or "")
            if len(tok & p_tok) >= _GOAL_CONNECT_OVERLAP and neg:
                return GateDecision(
                    outcome=GateOutcome.HOLD,
                    reason=f"hold:negates_problem_{p['id']}",
                )

        # Check 3 — Novel with goal/problem connection → ACCEPT (positive signal)
        for g in goals:
            g_tok = _tokens(g["title"] or "")
            if len(tok & g_tok) >= _GOAL_CONNECT_OVERLAP:
                return GateDecision(
                    outcome=GateOutcome.ACCEPT,
                    reason=f"accept:novel_connects_goal_{g['id']}",
                )
        for p in problems:
            p_tok = _tokens(p["title"] or "")
            if len(tok & p_tok) >= _GOAL_CONNECT_OVERLAP:
                if (
                    self._self_narrative is not None
                    and packet.confidence >= _NARRATIVE_CONFIDENCE_THRESHOLD
                ):
                    try:
                        self._self_narrative.write_narrative(
                            f"New insight connects to open problem '{p['title']}': "
                            f"{packet.content[:120]}",
                            "gate_accept_problem",
                            int(p["id"]),
                        )
                    except Exception as exc:
                        errors.record(
                            f"self_narrative gate trigger: {exc}",
                            source=_LOG_SOURCE, exc=exc,
                        )
                return GateDecision(
                    outcome=GateOutcome.ACCEPT,
                    reason=f"accept:novel_connects_problem_{p['id']}",
                )

        # Phase 24 — RESHAPE check (opt-in via packet metadata, D1=δ)
        # Existing five generative paths never set reshape_hint; zero organic RESHAPE.
        reshape_hint = packet.metadata.get("reshape_hint", False)
        reshape_depth = packet.metadata.get("reshape_depth", 0)
        if reshape_hint and reshape_depth < 2:
            return GateDecision(
                outcome=GateOutcome.RESHAPE,
                reason=f"reshape:hinted_depth_{reshape_depth}",
            )
        # depth >= cap: fall through to ACCEPT (cognitive-effort cap reached)

        # Default — novel, no conflict
        return GateDecision(
            outcome=GateOutcome.ACCEPT,
            reason="accept:novel_no_conflict",
        )

    # ── Substrate reads ───────────────────────────────────────────────────────

    def _read_substrate(self):
        """Read T1 anchors, active goals, open problems, recent beliefs.

        All four reads are fresh per call (Design D1=α). Total cost ~1ms.
        """
        anchors = []
        goals = []
        problems = []
        recent = []

        try:
            anchors = self._beliefs_reader.read(
                "SELECT id, content FROM beliefs "
                "WHERE tier=1 AND confidence > 0.8 AND locked=1 "
                f"LIMIT {_ANCHOR_LIMIT}"
            )
        except Exception as exc:
            errors.record(f"gate anchor read: {exc}", source=_LOG_SOURCE)

        try:
            recent = self._beliefs_reader.read(
                "SELECT content FROM beliefs "
                "WHERE source IN ('fountain_insight', 'synergized', "
                "'precipitated_from_dynamic', 'behavioural_observation') "
                f"ORDER BY created_at DESC LIMIT {_RECENT_LIMIT}"
            )
        except Exception as exc:
            errors.record(f"gate recent read: {exc}", source=_LOG_SOURCE)

        if self._conversations_reader is not None:
            try:
                goals = self._conversations_reader.read(
                    "SELECT id, title FROM goals "
                    "WHERE state='active' ORDER BY priority DESC LIMIT 5"
                )
            except Exception as exc:
                errors.record(f"gate goals read: {exc}", source=_LOG_SOURCE)

            try:
                problems = self._conversations_reader.read(
                    "SELECT id, title FROM open_problems "
                    "WHERE state='open' ORDER BY last_touched_at DESC LIMIT 5"
                )
            except Exception as exc:
                errors.record(f"gate problems read: {exc}", source=_LOG_SOURCE)

        return anchors, goals, problems, recent

    # ── Logging ───────────────────────────────────────────────────────────────

    def _log_decision(self, packet: ThoughtPacket, decision: GateDecision) -> None:
        try:
            self._beliefs_writer.write(
                "INSERT INTO gate_decisions "
                "(ts, source_node, outcome, reason, latency_ms, "
                "content_preview, branch_id, confidence) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    time.time(),
                    packet.source_node,
                    decision.outcome.value,
                    decision.reason,
                    round(decision.latency_ms, 3),
                    packet.content[:80],
                    packet.branch_id,
                    packet.confidence,
                ),
            )
        except Exception as exc:
            errors.record(
                f"gate_decisions log error: {exc}", source=_LOG_SOURCE, exc=exc
            )
